### ISSUE TITLE
Suggestion: Dispatch cross-server commands.

### ISSUE THREAD

**Issue by ShadyEntry** [Fireflies/BungeeEssentials#1]
**Command:** Yes
**Commands:** /dispatchserver <server name> <commands>, /dispatch <commands>
**Permission:** Yes
**Permissions:** Doesn't matter specifically to me what the node is.
**Description:** As with LilyEssentials, the ability to perform cross-server commands with /dispatch & /dispatchserver. (Example: /dispatch factions manuadd Nertch Owner)

**Comment by csh** [comment]
Hi there!

First up thankyou for using the issue tracker for this :)
Secondly I'm afraid I'm going to have to disappoint, please see [this](http://www.spigotmc.org/threads/bungeeessentials.32592/page-3#post-503454) post about why I don't want to include it.

With LilyEssentials we used what was basically a third party implementation of the plugin messaging channel so it didn't matter if there was a player online or no, but with BungeeCord I'm afraid we don't have this feature.

I recommend you use [vemacs/ExecuteEverywhere](https://github.com/vemacs/ExecuteEverywhere) in place of this, I _may_ experiment with how to do this in the future - I'd really rather avoid sockets though which seems to be the only way I can do this without forcing things like Redis on server owners.
