### ISSUE TITLE
Add integration

### ISSUE THREAD

**Issue by csh** [Fireflies/BungeeEssentials#10]
TODO: Add integration with [Fireflies/SukiBans](https://github.com/Fireflies/Sukibans) once the mute system has been completed. Possibly allow registration of custom [`IntegrationProvider`](https://github.com/PantherMan594/BungeeEssentials/blob/master/src/main/java/com/pantherman594/gssentials/integration/IntegrationProvider.java) classes.

Until mute system is complete then enjoy a kitten photo.
![Cute](http://placekitten.com/g/500/220)

**Comment by csh** [comment]
Have any thoughts about custom providers @PantherMan594? I certainly think it'd make integration with BungeeEssentials a more attractive idea if we gave developers the ability to do so.

**Comment by PantherMan594** [comment]
I'll be adding an API in the next update... hopefully tomorrow?

**Comment by PantherMan594** [comment]
As for the other way around (custom IntegrationProviders), I don't have the slightest idea of how to do that.
