### ISSUE TITLE
My Awesome Suggestion

### ISSUE THREAD

**Issue by kadika66** [Fireflies/BungeeEssentials#11]
**Command:** yes
**Commands:** mute and ipban
**Permission:** yes 
**Description:** i need a ipban for Bungee and i like mute for the network

**Comment by pantherman594** [comment]
For those you can use another plugin like BungeeAdminTools (BungeeEssentials hooks into BungeeAdminTools and BungeeSuite for mutes).

**Comment by kadika66** [comment]
ok Thanks i will just use BungeeAdminTools
