### ISSUE TITLE
My Awesome Suggestion

### ISSUE THREAD

**Issue by UntouchedOdin0** [Fireflies/BungeeEssentials#12]
**Command:** yes
**Commands:** /find
**Permission:** nope
**Permissions:** none
**Description:** When you do /find it will tell you where the other player is. :D

Please try to follow the format displayed here: https://github.com/Albioncode/BungeeEssentials/blob/master/README.md

**Comment by pantherman594** [comment]
Already exists, https://github.com/PantherMan594/BungeeEssentials/wiki/Find
