### ISSUE TITLE
message and command logging

### ISSUE THREAD

**Issue by voigtman** [Fireflies/BungeeEssentials#15]
I recently had the displeasure of having a DDoS attack on my server after banning a hacker. After sifting through days of server and Bungee logs looking for evidence of premeditation I realized messages that are handled through BE are not logged anywhere. This seems to me to be a major security flaw. So my suggestion is to please generate a log for all messages and commands handled by BungeeEssentials. 

Secondly: Please add a method to disable a players ability to /msg /r either through the console or in-game as these commands are intercepted by the proxy plugin before they reach the server where most punishment systems actually run. /mute has no effect on players' ability to talk through messages currently.

**Comment by pantherman594** [comment]
For the logs, I'll add a module to log all commands, server switches, server joins/quits, and chats to the console and ultimately to the Bungee logs. For that I use BungeeWeb, but I'll add it anyways.

I'll add a /bmute command for the second request.

**Comment by voigtman** [comment]
Thank you!
