### ISSUE TITLE
My Awesome Suggestion

### ISSUE THREAD

**Issue by Bron4** [Fireflies/BungeeEssentials#2]
**Command:** no
**Commands:** no
**Permission:** yes
**Permissions:** spam
**Description:** minimal spam filtering to keep certain words, or repeating msgs over and over.
on the /msg command

**Comment by csh** [comment]
An awesome suggestion indeed :stuck_out_tongue_winking_eye:

**Comment by csh** [comment]
Issue is partially complete.
Have added regex support so that admins may selectively block certain words/regex patterns.

**Comment by csh** [comment]
I have implemented a levenshtein distance calculator to add a layer of spam protection, you can find it in release 1.0.6, available on the releases page and the spigot forums.
