### ISSUE TITLE
Issues with color codes

### ISSUE THREAD

**Issue by ericaaberg** [Fireflies/BungeeEssentials#21]
Color codes didnt seem to work on my server with the join and leave messages. Using Bungeecord Build #1093

**Comment by pantherman594** [comment]
They're working for me, can you provide your messages.yml and config.yml?

**Comment by ericaaberg** [comment]
Sure give me a few seconds

**Comment by ericaaberg** [comment]
Heres what happens: http://prntscr.com/9o83pe
http://pastebin.com/uPfBAxsx

**Comment by pantherman594** [comment]
This error:

```
23:38:55 [INFO] [BungeeEssentials] You are running the latest version of BungeeEssentials (v247)!
23:38:55 [SEVERE] java.nio.file.FileAlreadyExistsException: plugins\BungeeEssentials\config_v246.yml
23:38:55 [SEVERE]     at sun.nio.fs.WindowsFileCopy.copy(Unknown Source)
23:38:55 [SEVERE]     at sun.nio.fs.WindowsFileSystemProvider.copy(Unknown Source)
23:38:55 [SEVERE]     at java.nio.file.Files.copy(Unknown Source)
23:38:55 [SEVERE]     at com.pantherman594.gssentials.utils.Updater.updateConfig(Updater.java:108)
23:38:55 [SEVERE]     at com.pantherman594.gssentials.utils.Updater.update(Updater.java:78)
23:38:55 [SEVERE]     at com.pantherman594.gssentials.BungeeEssentials.onEnable(BungeeEssentials.java:104)
23:38:55 [SEVERE]     at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:220)
23:38:55 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:256)
23:38:55 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:54)
23:38:55 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
```

will be fixed in the next update. The other error is with your BungeeCord config (it also doesn't need 4 gb of ram, 512 mb is enough). Can you send me the contents of your messages.yml file?

**Comment by ericaaberg** [comment]
This is just from my computer, rushed with the ram but will fix! :) Here is the messages.yml: http://pastebin.com/t7QGpx8S and messages_v246.yml: http://pastebin.com/JmAy2gCD

**Comment by pantherman594** [comment]
Can you provide a screenshot of the join/quit messages? The ones in those config files are different from the screenshot you provided earlier (http://prntscr.com/9o6plp)

**Comment by pantherman594** [comment]
Try the new update. If you still have the problem, feel free to reopen the issue.
