### ISSUE TITLE
Odd "A" like character

### ISSUE THREAD

**Issue by hsyyid** [Fireflies/BungeeEssentials#24]
Many commands in this plugin have a weird `A` like character, most likely caused by a decompiler trying to decompile the character `§`

One command where this occurs is in the `/message` command.

**Comment by pantherman594** [comment]
Can you provide a screenshot?

**Comment by hsyyid** [comment]
Sure! [Screenshot](https://gyazo.com/895c014eb01cad6e2bab83d72d8c214b)

**Comment by pantherman594** [comment]
Can you send me your messages.yml?

**Comment by pantherman594** [comment]
Are you using `§` in your config to set colors? If so, you don't need to, you can use `&` and it'll automatically be converted..

**Comment by hsyyid** [comment]
I actually posted this issue for a friend of mine who uses this plugin, he'll answer your questions in a bit.

**Comment by Darktilldawn** [comment]
http://pastebin.com/FRi2RRhW

**Comment by pantherman594** [comment]
Try using `{{ RAQUO }}` instead of `»`. Did this happen in previous versions?

**Comment by Darktilldawn** [comment]
It's happened since I started using the plugin, back on v246 I think? But I've never changed anything inside of the messages.yml

**Comment by pantherman594** [comment]
It could be a problem with how you're encoding it, try saving it in ANSI or UTF-8.

**Comment by voigtman** [comment]
This was an issue for me as well, right out of the box. I just switched it to -> on my server.

**Comment by pantherman594** [comment]
Closed. Feel free to open if not solved.
