### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Obatunde** [Fireflies/BungeeEssentials#25]
Sorry for the very newbie question, but how do I install this plugin?
I understand the basic about downloading and placing in the plugins folder of my bungeecord, but do I need anything else on the bukkit or spigot servers?
Right now I am using bukkit essentials individually on each server.

**Comment by pantherman594** [comment]
All you need to do is put it in your bungeecord plugins folder. It isn't related to bukkit essentials.

**Comment by Obatunde** [comment]
Thank you very much.

**Comment by pantherman594** [comment]
Closed. Feel free to open if not solved.
