### ISSUE TITLE
how to setup an alias for /server command

### ISSUE THREAD

**Issue by Fortuneskills** [Fireflies/BungeeEssentials#27]
I want player to use the /lobby command to teleport to a hub server. The command in BungeeCord for teleporting to this server s /server hub 
This works.
When creating an alias I get an permission error

I created this alias:
aliases:
  lobby:
- 'server hub'

Please help me what am I doing wrong

**Comment by PantherMan594** [comment]
You need to give them the permission `gssentials.alias.lobby`, or
`gssentials.alias` for all aliases.
https://github.com/PantherMan594/BungeeEssentials/wiki#commands-and-permissions

**Comment by pantherman594** [comment]
You need to give them the permission `gssentials.alias.lobby`, or
`gssentials.alias` for all aliases.
https://github.com/PantherMan594/BungeeEssentials/wiki#commands-and-permissions
