### ISSUE TITLE
Issue with Bungeecord 1135?

### ISSUE THREAD

**Issue by ChiuChiuTrains** [Fireflies/BungeeEssentials#29]
Hello PantherMan594,

I seem to have run into issues when I attempted to use build 2.5.4 with bungeecord build 1135 (latest build)

It is very peculiar since it was working perfectly fine before we updated. Could you give us a hand as to why the plugin is not working? I've actually attempted to downgrade back to your build 2.5.2, but alas the server still does not recognize the commands.

Bungee Essentials config.yml: http://pastebin.com/jEDvidvM

Proxy server logs: 
 -> 2.5.4 version - http://pastebin.com/YmZDzK0V
 -> 2.5.2 version - http://pastebin.com/J2rLxMcy

I apologize in advance if there are other issues surrounding the one with bungee essentials. I'm not very knowledgeable about stack traces so I tried to cut out anything that wasn't error related in the pastes. If you require more specific and shorter pastes, I'll try my best to filter out the other things in an additional comment.

Thank you for your support and I hope you can help :)
- WSN Network

**Comment by pantherman594** [comment]
What version of Java are you running? Versions 2.5.3+ require Java 8 or higher.

**Comment by ChiuChiuTrains** [comment]
I'll have to contact my host about that. Do you believe that would solve the issue?

**Comment by pantherman594** [comment]
Yes, the "major.minor version 52.0" refers to Java 8.

**Comment by ChiuChiuTrains** [comment]
Thank you for the quick response earlier. The host JUST updated our bungeecord proxy to java 8 and it is now recognizing it.

Now it seems that many of our server plugins are overridden and I receive the "&cYou do not have permission to execute this command!"

I'm not sure if this is because of bungee essentials, but it seems to be the only change I added to the server. I'm attempting to play with the config, but I would appreciate it if you had any insight on this as well.

If this requires a more formal layout, I will gladly open a new issue.

Thank you,
- WSN Network

**Comment by pantherman594** [comment]
Which commands are you trying to run? All the default commands and permissions can be found [here](https://github.com/PantherMan594/BungeeEssentials/wiki#commands-and-permissions).

**Comment by ChiuChiuTrains** [comment]
Please excuse my idiocy, I simply needed to comment out some commands to disable them entirely.

Thank you so much for your assistance. Everything seems to be in working order now.
- WSN Network
