### ISSUE TITLE
SocialSpy Bug

### ISSUE THREAD

**Issue by ghost** [Fireflies/BungeeEssentials#3]
**Description:** SocialSpy does not work across servers. You can only see messages sent from the server you are on but not sent from another server to another server or from another server to your own

**Steps to replicate:** Have an account go on a server and message himself while watching from an alt that is on a different server.

**P.S.:** Neither account had spy.exempt when I tested this

**Comment by csh** [comment]
This was actually done by design believe it or not :P

Think it's worth adding the option to toggle whether it's global or not?

**Comment by ghost** [comment]
I would say it'd be worth it to have a global toggle command/permission. I just assumed it would allow it since it has an option to show what server the message was sent from :P. :+1:

**Comment by ghost** [comment]
Also is there anyway you can add a way to choose in the config if social spy is default on or off and/or a way that people only have GSpy on certain servers like all servers they're op'd on but only servers they're op'd on instead of all servers on the network. I haven't looked into this though so if it's already a feature Imma feel stupid xD

**Comment by csh** [comment]
Per server permissions are documented _I think_. Bungee alone cannot determine operator status I'm afraid so that one is a nono :P

**Comment by csh** [comment]
Also right now I'm quite busy (looking for work + moving about) so I apologise if I ever take a while to reply
