### ISSUE TITLE
Syncing with player's colored names, etc

### ISSUE THREAD

**Issue by SpaZMonKeY777** [Fireflies/BungeeEssentials#30]
So with plugins like Essentials, they can show a players rank/color/tag/etc even when they are /msg'ing in private, but is this possible at all with BungeeEssentials? I can't imagine it's possible to hook into Essentials, since it isn't on BungeeCord but on the bukkit server itself, but it would be nice to have the players colored names, etc show up when they are chatting in private as well, etc. If it's not possible though, I completely understand, just thought I ask :)

Thanks for all your work!

**Comment by pantherman594** [comment]
Technically it's possible with a plugin on your Spigot/Bukkit server as
well, but I think that might bloat BungeeEssentials a little too much and
make it not just the "essentials". I could make it hook into a Bungee
permissions plugin such as BungeePerms for prefixes, but you would have to
setup the prefixes for color (I don't think it supports nick) there as
well. I could also make a nicknaming command in BungeeEssentials.
