### ISSUE TITLE
Network-Wide Join & Quit Messages

### ISSUE THREAD

**Issue by Hwiggy** [Fireflies/BungeeEssentials#31]
**Steps to replicate:** Set a custom join & or quit message in your config, enable join & quit messaging network-wide
**BungeeEssentials Version:** 2.5.3
**Minecraft Version:** 1.8.9
**Description:** Join messages get delimited, causing an ugly, asynchronous chat to appear for the person who joins the server. Recommend adding the join message to have the highest priority but remove the new line. Screenshot: http://prntscr.com/atdso9

**Comment by pantherman594** [comment]
Sorry, I'm not sure I understand your problem. Is it that you don't want the join message to show for the player joining?

**Comment by Hwiggy** [comment]
No, I don't want the empty line AFTER the join message.

**Comment by pantherman594** [comment]
I'm not able to replicate this, can you send me your messages config? (or just the part for the join message)

**Comment by Hwiggy** [comment]
http://paste.ee/p/XnmN2

**Comment by pantherman594** [comment]
I copied your config, this is what I got: http://i.pantherman594.com/17-04-16_Q4a.png. Could it be something else that is creating that empty line?

**Comment by Hwiggy** [comment]
NoCheatPlus seems to be doing it (After joining & leaving after turning off various plugins)
My apologies.
http://prntscr.com/atflv0
