### ISSUE TITLE
Delay, interval and Server

### ISSUE THREAD

**Issue by Ironic8b498** [Fireflies/BungeeEssentials#32]
I would like to figure out how to use the announcements.AnncName keys? got about 12 messages I scroll on servers and some of the messages should not be sent to them. need a good example on what to do?

**Comment by pantherman594** [comment]
I just updated the Announcement page on the wiki to provide an [example](https://github.com/PantherMan594/BungeeEssentials/wiki/Announcement#example). Hope that helps!
