### ISSUE TITLE
hello i have problem with Playerdata

### ISSUE THREAD

**Issue by SirAbdullah** [Fireflies/BungeeEssentials#33]
every 3 or 4 days if someone msg someone he cant send msg to him i see error its say chcek console with any bungeeessentials commands even /gssreload and if i delete PlayersData folder and do /gssreload will work fine after 3 or 4 or 2 days will come back the same problem why?

**Comment by pantherman594** [comment]
What BungeeEssentials version are you running? Are there any errors in the console?

**Comment by SirAbdullah** [comment]
2.5.4

**Comment by SirAbdullah** [comment]
i dont take a look on a console

**Comment by pantherman594** [comment]
Well if you don't have any specific errors from the console for me, I'm sorry I don't really know how i can help you. Maybe you can try downloading the latest version? (2.5.5)

**Comment by SirAbdullah** [comment]
take a look http://pastebin.com/uLFHGTb4

**Comment by pantherman594** [comment]
The next time this happens can you send me your player data file before resetting it? (in `plugins/BungeeEssentials/playerdata/your-uuid.yml`)

**Comment by SirAbdullah** [comment]
its much pleyers data i can send u 1 file http://pastebin.com/U4yeEDf3 look

**Comment by SirAbdullah** [comment]
this problem show to all players can msg and staffchat and any bungee ess commands not me only

**Comment by pantherman594** [comment]
I can't view that file, can you send it again?

**Comment by SirAbdullah** [comment]
Sure see http://pastebin.com/6V5323Gf

**Comment by SirAbdullah** [comment]
Can't not can sorry .

**Comment by pantherman594** [comment]
It looks fine, doesn't seem to have anything wrong with it. Is this from when you have an error?
