### ISSUE TITLE
Bug Report - /r nor working properly

### ISSUE THREAD

**Issue by voigtman** [Fireflies/BungeeEssentials#34]
**Steps to replicate:** <steps>
player 1 sends message
player 2 types '/r some message' and the message does not return to player 1.  

**BungeeEssentials Version:** 2.5.6

Bungee Version: 1156
**Minecraft Version:** <mcversion> Spigot 1.8.8
**Description:** <description>

**Comment by pantherman594** [comment]
In version 2.5.0 I added a 3-second delay before messages are recorded for replies. Could this be the issue? (Try waiting a little longer before using /r)

**Comment by voigtman** [comment]
no, players are not able to reply to the original sender unless both use /msg first. 
Also, I toggled the message recently (just to see what that did) and this has been the case since

**Comment by pantherman594** [comment]
Turning messaging off prevents you from getting messaged (unless by an admin). Which error, if any, does it throw when you try to use /r?

**Comment by voigtman** [comment]
If you've just logged in, and someone messaged you, and you type /r you will get "Nobody has messaged you recently." 
you have to use /msg to reply to the incoming message. 
however, if the scenario involves 3 players and player 3 messages one of the other 2, /r only continues the communication between the first 2 players. again, to initiate the reply you must first /msg player3

**Comment by pantherman594** [comment]
Is messaging enabled for both?

**Comment by voigtman** [comment]
messaging is enabled, I thought that was a server-wide command....

**Comment by pantherman594** [comment]
No, it's per-player. If you don't want anybody to message you, you turn messaging off for yourself. Is messaging enabled for both players (especially the recipient)?

**Comment by voigtman** [comment]
yes it's on

**Comment by pantherman594** [comment]
Try turning messaging _off_ for the recipient (I might have made a mistake in the code), send the message, and then turn it back on again to reply.

**Comment by voigtman** [comment]
ok i'll test that... but how do I do that for another player?

**Comment by pantherman594** [comment]
Either tell them to do `/msg off` or you do it and have the other player message you, and you reply.

**Comment by voigtman** [comment]
so that permits them to reply again.. but only for that one time. if they message another person and player 3 sends a message /r doesn't go back to player 3

**Comment by pantherman594** [comment]
I'll try to fix that right now and send you a version to test, and see if it fixes that other problem too.

**Comment by voigtman** [comment]
ok, cool thank you

**Comment by pantherman594** [comment]
Try this: http://ci.pantherman594.com/job/BungeeEssentials/99/artifact/target/BungeeEssentials.jar

**Comment by voigtman** [comment]
Testing now

**Comment by voigtman** [comment]
that seems to have fixed it
