### ISSUE TITLE
Spam bug

### ISSUE THREAD

**Issue by SirAbdullah** [Fireflies/BungeeEssentials#35]
if some one type command more than 22 or 12 like this will allow him to spam

http://prntscr.com/b6zaq8

**Comment by pantherman594** [comment]
What command(s) are they running?

**Comment by SirAbdullah** [comment]
i spam unknown command but all command have this problem!

**Comment by pantherman594** [comment]
Are you running the same command multiple times? Or are you running different commands each time? Is spam-command enabled?

**Comment by SirAbdullah** [comment]
multipe times not diffrent and i sure enabled spam-command its work but after much spam will allowed to you to spam this command
