### ISSUE TITLE
Add a /seen Command

### ISSUE THREAD

**Issue by ThemInspectors** [Fireflies/BungeeEssentials#38]
**Commands:** /seen [Player/UUID]
**Permissions:** gessentials.seen and gessentials.seen.geoip gessentials.seen.uuid etc.
**Description:**  Every Bungee Server needs a /seen command w/ last server been on, customizable message, Also known as (previous Minecraft names) and If enabled geo-ip with separate perms for geo-ip also With UUID

**Comment by pantherman594** [comment]
I'll add a /seen command in the next version. However, I'm not so sure about geoip, I think it would just make the plugin unnecessarily larger.

**Comment by pantherman594** [comment]
https://github.com/PantherMan594/BungeeEssentials/commit/e75773f77d0a74573520c49c38dfdc1c9eaa41e0
