### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by NickParks** [Fireflies/BungeeEssentials#40]
Hello!

After using your plugin for a few hours we discovered this bug. It actually ends up breaking the entire plugin and Bungee ends up crashing every now and then. Full log below.

https://gist.github.com/SirNickParks/3ca7379f8e196d96273df8d7685e7869

**Comment by pantherman594** [comment]
There's a bug that playerdata breaks if someone joins while the plugin is
still starting up (first three seconds, when a player joins before
playerdata starts up), could that be the cause of this?

**Comment by NickParks** [comment]
Not that I can see.

The proxy holds just fine for a bit until we see massive error spam appear. Yet to find a direct cause.

**Comment by pantherman594** [comment]
Is there anything in the logs right before this happens?

**Comment by NickParks** [comment]
I'll check the logs in a second;

However running the "reload" method in the onEnable of the plugin instead of 3 seconds later (as you schedule it) seems to work just fine? Is there any reason why you wait 3 seconds before running it?

https://github.com/PantherMan594/BungeeEssentials/blob/master/src/main/java/com/pantherman594/gssentials/BungeeEssentials.java#L107

**Comment by pantherman594** [comment]
It runs 3 seconds later to override the default BungeeCord '/glist' '/alert' and '/send'. In the next update it'll run "reload" immediately, and then again 3 seconds later to override the commands.

**Comment by pantherman594** [comment]
Actually... in the update I'll make it disable the default bungee commands
