### ISSUE TITLE
Permissions not working

### ISSUE THREAD

**Issue by arch2978** [Fireflies/BungeeEssentials#41]
I have permissions setup in my PEX exactly as you have them in the command/permission listings, but when I use the commands, even as op, they don't work.

**Comment by pantherman594** [comment]
This is a Bungee plugin. Install it on your Bungee server, setup permissions in Bungee.

**Comment by arch2978** [comment]
It is installed on my bungee server, I was just talking to you on the forums.

**Comment by pantherman594** [comment]
2ca9540665b9e168aa6e955659f6bce26a162a52
