### ISSUE TITLE
A Suggestion

### ISSUE THREAD

**Issue by benjaminbrassart** [Fireflies/BungeeEssentials#42]
**Commands:** "/ban <player> <[duration]> <[reason]>"
**Permissions:** "essentials.ban", "essentials.ban.unlimited"
**Description:** "Bans players."

**Comment by pantherman594** [comment]
I will consider adding it in the future.

**Comment by benjaminbrassart** [comment]
Thanks you c:

**Comment by Volander** [comment]
Would be very usefull when/if you add the command that you could see the banreason, how long time i left on the ban and who banned the player in /lookup

Just something I miss from all the other plugins.

**Comment by pantherman594** [comment]
Yeah I will add that when I add the command.
