### ISSUE TITLE
msg?

### ISSUE THREAD

**Issue by voigtman** [Fireflies/BungeeEssentials#44]
I have not run into this issue before but it's been a while since I've done a major update - I recently updated to the latest Bungee and BungeeEssentials and updated the servers and what not. I did add ProxySuite and VanillaPod. Are you aware of any interactions these plugins may have? 

Right now I can send a /msg command and it hits bungee fine - no errors are generated but I only see the "Sorry, no player was found." error in chat. This is the case when chatting across the proxy but If i am on the very same server, it works fine. ideas? I am running 3 versions on MC on the same proxy. 1.8.8, 1.10.2 and 1.11 (which is what vanillapod is for)

**Comment by pantherman594** [comment]
Players need another permission to msg across servers,
gssentials.message.global. This should've been on the wiki, sorry about
that.

**Comment by voigtman** [comment]
Ah! Thank you very much

**Comment by pantherman594** [comment]
No problem!
