### ISSUE TITLE
HELP, BUG

### ISSUE THREAD

**Issue by nickcat5** [Fireflies/BungeeEssentials#45]
People can do /cspy without perm and when i do /cspy i don't see commands

**Comment by pantherman594** [comment]
Is it only /cspy, and not /spy? What version are you running? What BungeeCord version do you have? Are there any errors in the console/log?

**Comment by nickcat5** [comment]
um yes I'm running 1.10.2  wait no its both for me. And no errors in log in console.

**Comment by nickcat5** [comment]
Wait never mind I just figured out the problem, I was adding too much groups.
