### ISSUE TITLE
BungeeEssentials can't be loaded by Spigot due to Class definition error

### ISSUE THREAD

**Issue by HariSeldon51** [Fireflies/BungeeEssentials#46]
Hello!

I'm having some trouble loading Bungee Essentials on my Spigot server. Note that this is not urgent for my server, so the priority on this is low. I know you're on vacation right now -- please enjoy it! :)

Here are the details:

**Steps to replicate:** 

- Start the Spigot server
- Receive error in the startup log when server attempts to load BungeeEssentials
- Redownloaded most recent stable build of BungeeEssentials from Jenkins (from Dec. 31st)
- Uploaded stable build of BungeeEssentials to server and restarted
- Still receive same error on server restart

**BungeeEssentials Version:** Jenkins Build #127; Spigot Version number for BungeeEssentials 12.6.4

**Minecraft Version:** 1.11.2

**Description:** <description>

I receive the following error in the console when attempting to restart the server:

> [12:40:16] [Server thread/INFO]: Starting minecraft server version 1.11.2
> [12:40:16] [Server thread/INFO]: Loading properties
> [12:40:16] [Server thread/INFO]: Default game type: SURVIVAL
> [12:40:16] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-7d78b81-27dd3ca (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)
> [12:40:16] [Server thread/INFO]: Debug logging is disabled
> [12:40:16] [Server thread/INFO]: Server Ping Player Sample Count: 12
> [12:40:16] [Server thread/INFO]: Using 4 threads for Netty based IO
> [12:40:16] [Server thread/INFO]: Generating keypair
> [12:40:17] [Server thread/INFO]: Starting Minecraft server on 198.154.103.83:25565
> [12:40:17] [Server thread/INFO]: Using epoll channel type
> [12:40:17] [Server thread/INFO]: Set PluginClassLoader as parallel capable
> [12:40:17] [Server thread/ERROR]: Could not load 'plugins/BungeeEssentials.jar' in folder 'plugins'
> org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: net/md_5/bungee/api/plugin/Plugin
> 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[spigot-1.11.jar:git-Spigot-7d78b81-27dd3ca]
> 	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot-1.11.jar:git-Spigot-7d78b81-27dd3ca]
> 	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot-1.11.jar:git-Spigot-7d78b81-27dd3ca]
> 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.loadPlugins(CraftServer.java:301) [spigot-1.11.jar:git-Spigot-7d78b81-27dd3ca]
> 	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:204) [spigot-1.11.jar:git-Spigot-7d78b81-27dd3ca]
> 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [spigot-1.11.jar:git-Spigot-7d78b81-27dd3ca]
> 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
> Caused by: java.lang.NoClassDefFoundError: net/md_5/bungee/api/plugin/Plugin
> 	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_112]
> 	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_112]
> 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_112]
> 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[?:1.8.0_112]
> 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_112]
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[?:1.8.0_112]
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[?:1.8.0_112]
> 	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_112]
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[?:1.8.0_112]
> 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.11.jar:git-Spigot-7d78b81-27dd3ca]
> 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.11.jar:git-Spigot-7d78b81-27dd3ca]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_112]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_112]
> 	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_112]
> 	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_112]
> 	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.11.jar:git-Spigot-7d78b81-27dd3ca]
> 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot-1.11.jar:git-Spigot-7d78b81-27dd3ca]
> 	... 6 more
> Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.plugin.Plugin
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_112]
> 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.11.jar:git-Spigot-7d78b81-27dd3ca]
> 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.11.jar:git-Spigot-7d78b81-27dd3ca]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_112]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_112]
> 	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_112]
> 	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_112]
> 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_112]
> 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[?:1.8.0_112]
> 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_112]
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[?:1.8.0_112]
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[?:1.8.0_112]
> 	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_112]
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[?:1.8.0_112]
> 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.11.jar:git-Spigot-7d78b81-27dd3ca]
> 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.11.jar:git-Spigot-7d78b81-27dd3ca]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_112]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_112]
> 	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_112]
> 	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_112]
> 	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.11.jar:git-Spigot-7d78b81-27dd3ca]
> 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot-1.11.jar:git-Spigot-7d78b81-27dd3ca]
> 	... 6 more

Please feel free to let me know if you need additional information -- I'll be happy to send you the entire log file if needed. Thanks very much -- hope you have a good day and that your vacation is treating you well!

Thanks,
Will

**Comment by pantherman594** [comment]
Hey,
BungeeEssentials is a BungeeCord plugin, not a Spigot plugin. If you want to use it, you need to add it to your BungeeCord plugins folder.
David
