### ISSUE TITLE
Hey, so i have a bug and thew plugin will not load onto my bungee server., The version is .1.7.9 bungee version : latest 

### ISSUE THREAD

**Issue by Bluqe** [Fireflies/BungeeEssentials#47]
**Steps to replicate:** Not sure what that means
**BungeeEssentials Version:** Latest
**Minecraft Version:** 1.7.10
**Description:** I put it in the plugins but will not load?

**Comment by pantherman594** [comment]
What bungeecord build are you running?

**Comment by Bluqe** [comment]
How would i check this?

**Comment by Bluqe** [comment]
http://prntscr.com/dvnyhg

**Comment by pantherman594** [comment]
That version is fine for me. What error are you getting?

**Comment by Bluqe** [comment]
None, its not even loading?

**Comment by Bluqe** [comment]
Any thing you can help with?

**Comment by pantherman594** [comment]
If it's not loading and there are no errors... are you sure you put it in the BungeeCord plugins folder? If you did and it's not loading, there should be an error when BungeeCord starts up and tries to load the plugin.
