### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Bluqe** [Fireflies/BungeeEssentials#49]
Hey, i have it all working. But no colors are coming through?
http://prntscr.com/dw22fh

**Comment by pantherman594** [comment]
Why are you opening new bug reports? Just continue the same thread. Did you change the config at all?

**Comment by Bluqe** [comment]
No

**Comment by pantherman594** [comment]
Are there any errors in the console?

**Comment by Bluqe** [comment]
Nope: 15.01 15:37:34 [Server] BungeeEssentials Registered 20 commands successfully
15.01 15:37:34 [Server] BungeeEssentials Loaded 8 rules from config
15.01 15:37:34 [Server] INFO donate.myserver.com
15.01 15:37:34 [Server] ! Donate to support our server!
15.01 15:37:34 [Server] BungeeEssentials Enabled announcements
15.01 15:37:34 [Server] BungeeEssentials Loaded 2 announcements from config
15.01 15:37:34 [Server] BungeeEssentials Enabled aliases
15.01 15:37:34 [Server] BungeeEssentials Loaded 4 aliases from config
15.01 15:37:34 [Server] BungeeEssentials Enabled the chat logger

**Comment by pantherman594** [comment]
Try deleting the entire BungeeEssentials folder and let it regenerate

**Comment by Bluqe** [comment]
Ok, would it be because im on 1.7.10 bungee?

**Comment by pantherman594** [comment]
I doubt it, colors are working fine for me (though I'm only looking at console, maybe colors aren't working for players, but it's very unlikely that colors would work for console and not players).

**Comment by Bluqe** [comment]
No, colors

**Comment by pantherman594** [comment]
Can you send your proxy,log.0 file?

**Comment by Bluqe** [comment]
Ok

**Comment by Bluqe** [comment]
http://pastebin.com/W9pcfGNR

**Comment by pantherman594** [comment]
According to that it looks like the colors are working. It might be because of BungeeCord, you can use newer versions with 1.7.10 Spigot.

**Comment by pantherman594** [comment]
Just tested it on 1.7.10, colors are working for both client and console.
