### ISSUE TITLE
Player quit announcement

### ISSUE THREAD

**Issue by rob1998** [Fireflies/BungeeEssentials#50]
The join announcement displays on all connected servers, but the quit announcement only displays on the server that the player was on

**Comment by pantherman594** [comment]
Do they have the `gssentials.announce.quit` permission?

**Comment by rob1998** [comment]
Yes, the situation has changed a bit, without me changing anything: now it's random wether players get notified when another player leaves from another server

**Comment by pantherman594** [comment]
What version of BungeeEssentials are you running? What version of BungeeCord? Are there any errors in the console? Check to make sure they have the permissions to get a join/quit announcement.

**Comment by Volander** [comment]
I am setting up my bungee server and so far I only have one world, when my test character leaves the server I do not get any announcement, however I get one when it joins.

I have the gssentials.announce.join and gssentials.announce.quit permission on the defaut group at my bungee server which all players are a member of.

I use BungeeEssentials 2.6.4 and running spigot 1.11.2, also using LuckPerms v2.17.45 as the permission plugin.

**Comment by pantherman594** [comment]
I have been unable to reproduce this. Can you check and make sure the permissions are properly setup for the players?

**Comment by Volander** [comment]
https://cdn.discordapp.com/attachments/262883674670759936/279974995030048768/2017-02-11_14.57.28.png

The permissions my bungee group has. And all my users are a member of the default group
Still I only get the join messages, and nothing when they leave.

**Comment by pantherman594** [comment]
Can you send your messages.yml and config.yml?

**Comment by Volander** [comment]
http://pastebin.com/pRRfVqWC

**Comment by pantherman594** [comment]
Okay, I believe the problem is that LuckPerms is unloading the player's permissions when he disconnects, so when BungeeEssentials tries to check for it, it returns false because according to LuckPerms, the player has no permissions.
