### ISSUE TITLE
Error when starting bungeecord

### ISSUE THREAD

**Issue by dukedase** [Fireflies/BungeeEssentials#51]
When I start it (for the first time and every time thereafter)

https://i.gyazo.com/e7c0a4e4e82f71aabf61cf411c302ab3.png

**Comment by pantherman594** [comment]
Are you using the MySQL or SQLite configuration (SQLite by default)? If MySQL, does the database exist and is it setup? If SQLite, does the file exist? (playerdata.db, in your BungeeEssentials plugin folder)

**Comment by dukedase** [comment]
Hi, sorry for late response.  I was using whatever the default config had because the first time I tried running the proxy with it in the folder it wouldn't work.  So I assume it was SQLite and not MySQL.

I switched to a separate plugin because time was somewhat important, however I plan on using BE in the future
