### ISSUE TITLE
ProxyPingEvent Issue

### ISSUE THREAD

**Issue by AngellitoX** [Fireflies/BungeeEssentials#57]
Hello! I've been being spammed the whole day with the following message: 

https://pastebin.com/dxEUQNhK

I'm using ServerListPlus for a customized motd too, if it helps.

How could I fix this? Thank you in advance!

Note: Using the latest version of BungeeCord, and the latest version of Bungessentials. Greetings!

**Comment by pantherman594** [comment]
Remove the [hoverlist](https://github.com/PantherMan594/BungeeEssentials/wiki/Hover-list) module from config.yml.
