### ISSUE TITLE
MultiLog Error When Using a CDN

### ISSUE THREAD

**Issue by MeMyselfMC** [Fireflies/BungeeEssentials#7]
### Description

When using a Minecraft CDN plugin like the InAbate one, if you have the "multilog" option enabled, BungeeEssentials will get the player IP before the CDN plugin which means it won't get the real IP of the player, but the IP of the PoP they are connecting from. This results in the multilog feature breaking, not allowing more than X players to be connected from the same PoP.
### Steps to Replicate
1. Setup a BungeeCord network behind a Minecraft CDN like InAbate.
2. Install BungeeEssentials on the BungeeCord instance and make sure the "multilog" option is enabled.
3. Install the plugin of the CDN you're using.
4. Start up/restart the BungeeCord instance and get X players/alts/bots to join.
5. Ta-da!

This has only been tested on my network, and since I'm using InAbate, I can't be sure if it happens with other CDNs like ProxyPipe. The IP is _play.crewpvp.com_ if you need to test it and you don't use a CDN (or have a server at all).

**Comment by pantherman594** [comment]
What do you mean by CDN plugin? So from what I understand, you are using InAbate to protect your server from DDOS attacks (I think) and in doing so, it reroutes their ips, rendering the multilog feature useless. So does InAbate have a plugin to get their ips back, but you're saying that BungeeEssentials grabs their ip before the plugin fixes it?

**Comment by MeMyselfMC** [comment]
Yes, that is correct. InAbate has a plugin that forwards the real player IPs to BungeeCord, however BungeeEssentials grabs the player IPs before the InAbate plugin does, breaking multilog if it's enabled.

**Comment by pantherman594** [comment]
Can you send me its source/the plugin so I can see when it forwards the ip?

**Comment by MeMyselfMC** [comment]
PMed you on SpigotMC.

**Comment by csh** [comment]
``` java
if(ProxyServer.getInstance().getPluginManager().getPlugin("InAbate") != null) {
    // delay registration
}
```

As of SpigotMC/BungeeCord#954 it appears plugin descriptors allow a `softdepends` section so if the InAbate plugin is added here then the plugin should load before BungeeEssentials so that `PluginManager#getPlugin(String)` will be able to detect it, after that... well, how InAbate works will determine what needs to be done.

**Comment by pantherman594** [comment]
From what I see in the InAbate plugin, I think the only way to make it work would be to have it check the player's ip a couple seconds _after_ the player has logged in, and then kick the player if s/he has the same ip as another player online. Would that be okay?

**Comment by csh** [comment]
Know I don't really have much to do with the project anymore but [this](https://github.com/SpigotMC/BungeeCord/blob/master/event/src/main/java/net/md_5/bungee/event/EventHandler.java) might help you. Set the event priority to "one less" than the InAbate plugin subscribes at and it should (if the event priority works how one would assume it does) be processed after where the original event will have already been tampered with. Then again, this is assuming that the InAbate plugin modifies the event object.

**Comment by pantherman594** [comment]
It uses PlayerHandshakeEvent, would that still work? (Still don't know that much about BungeeCord)
With [this](https://www.dropbox.com/s/3q71iunwueewewj/BungeeEssentials.jar?dl=0), I set the priority to one less than InAbate's.

**Comment by MeMyselfMC** [comment]
@PantherMan594 Tested that and it seems to be working so far, I will PM you if something comes up. Would be great if you could update the plugin with this patch :)

**Comment by pantherman594** [comment]
Alright great!

**Comment by csh** [comment]
A PlayerHandshakeEvent just refers to the exchange of handshake packets between client and server, the server is sent the protocol version, hostname used to connect (how forced hosts are achieved I believe), server port, handshake state and optionally the username if the handshake state is set to 2 :stuck_out_tongue: 

Have marked the build as pre-release purely because there's only one report of it working :smile:
