### ISSUE TITLE
Remove spies on logout

### ISSUE THREAD

**Issue by pantherman594** [Fireflies/BungeeEssentials#8]
Spies were being removed on logout, so I decided to look into it and found this. This was added in version 1.0.5, and I was wondering if it was intentional? (Line 293 current version)

``` java
if (cspies.contains(uuid)) {
    cspies.remove(event.getPlayer().getUniqueId());
}

if (hidden.contains(uuid)) {
    hidden.remove(event.getPlayer().getUniqueId());
```

**Comment by csh** [comment]
Yeah, I figured some servers (if ones this large even used BungeeEssentials) may have a lot of people with access to spying functionality. With this in mind I thought it'd be best if the list entries were removed when they were no longer necessary. :smile:
