### ISSUE TITLE
My Bug Report

### ISSUE THREAD

**Issue by trustinlies** [Fireflies/BungeeEssentials#9]
**Description:** Turning off staff chat does not prevent staff chat messages from showing.
**Steps to replicate:** 
1. Type /sc off
2. Have another staff member send a staff chat message.
3. See the message and realize you shouldnt be. 

Hope this helps you :)

Please try to follow the format displayed here: https://github.com/Albioncode/BungeeEssentials/blob/master/README.md

**Comment by pantherman594** [comment]
Hi,
Turning it off/on toggles chatting in staff chat. If it is off, you chat in
regular chat. If it is on, you automatically chat in staff chat, without
having to prepend it with /staffchat

David Shen
